---
title: "2018 Winter-in-review and Spring Outlook"
---

## {-}
  
<div style="-webkit-columns: 2 300px;-moz-columns: 2 300px;columns: 2 300px;">
- Summer 2017 was the second driest and fifth warmest in Montana since record-keeping began in 1895.
- In the summer 2017, the lack of rainfall and brisk winds in eastern Montana led to a rapid onset severe drought, or a “flash drought”, across the state.
- By the middle of the century (e.g. 2050), summer conditions are expected to be significantly warmer but with more precipitation compared to the summer months of 2017
- During fall of 2017, Montana entered a La Niña event. La Niña events often bring cooler temperatures across the state as well as increased winter precipitation specifically to western Montana.
- For winter 2018, above average precipitation and below normal temperatures are forecasted across Montana, in line with a typical La Niña event. However, given the soil moisture deficit hanging on from last summer, it is too early to tell if this forecast will improve the spring growing season. Keep an eye on subsurface soil moisture levels, especially in eastern Montana.
</div>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      results = "hold",
                      eval.after = "fig.cap",
                      fig.width = 4.45,
                      fig.height = 2.54,
                      fig.retina = 4, 
                      fig.align = "center", 
                      out.width = '100%', 
                      collapse=TRUE,
                      cache=TRUE
)

# install.packages("devtools")
# devtools::install_github("mt-climate-office/mcor")
# source("https://bioconductor.org/biocLite.R")
# devtools::install_github("ecohealthalliance/fasterize")
# biocLite("rhdf5")

## Load all packages
all_packages <- c("mcor", # The Core MCO package
                  "FedData", "smapr", "rhdf5", # Package for data aquisition
                  "sf", "raster", "rgeos", "fasterize", "velox", # Packages for spatial processing
                  "magrittr", "tidyverse", "purrrlyr", # Packages for tidy code
                  "RColorBrewer", "htmlwidgets", "htmltools", "leaflet", "plotly",
                  "bibtex", "knitcitations", "kableExtra") # Plotting and rmarkdown

# devtools::install_bioc("rhdf5")
# purrr::walk(all_packages, devtools::install_cran, character.only = TRUE)
purrr::walk(all_packages, library, character.only = TRUE)

# Load other useful functions
list.files("../R", full.names = T) %>%
  purrr::walk(source)

```

